<a href="https://colab.research.google.com/github/superslic/python/blob/main/%EB%B0%B0%EC%97%B41.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = np.array(a)

print(x)

a


In [ ]:
x_col = np.array([[1], [2], [3], [4]])
print(x_col.shape)
print(x_col)


(4, 1)
[[1]
 [2]
 [3]
 [4]]


In [30]:
b = np.arange(1, 10)
B = np.reshape(b, (3,3))
B_slicing = B[0:2, 1:3]
print(B_slicing)

[[2 3]
 [5 6]]


In [42]:
b = np.arange(1, 10)
B = np.reshape(b, (3,3))
B_slicing = B[2:3, 0:4]
print(B_slicing)

[[7 8 9]]


In [45]:
b = np.arange(1, 10)
B = np.reshape(b, (3,3))
B_slicing = B[0:3, 2:4]
print(B_slicing)

[[3]
 [6]
 [9]]


In [52]:
b = np.arange(1, 10)
B = np.reshape(b, (3,3))
B_slicing = B[1:2, 0:2]
print(B_slicing)

[[4 5]]
